version: '3.8'

services:
  api:
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    # ports:
    #   - "5000:3000"
    # environment:
    #   - DATABASE_URL=postgres://postgres:pgpass@db:5432/mydb
    # depends_on:
    #   - db
    build: .
    ports:
      - "5000:3000"
    volumes:
      - .:/app                   # Bind mount: Map current folder to /app in container
      - /app/node_modules       # "Anonymous" volume: Don't overwrite container's node_modules
      # - type: bind
      #   source: .
      #   target: /app
      #   read_only: false
      # - /app/node_modules
    command: npm run dev        # can use nodemon for hot reload
    environment:
      - DATABASE_URL=postgres://postgres:pgpass@db:5432/mydb
  
  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pgpass
      - POSTGRES_DB=mydb
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pgdata: